---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - vpc.poridhi.io
  resources:
  - vpcs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vpc.poridhi.io
  resources:
  - vpcs/finalizers
  verbs:
  - update
- apiGroups:
  - vpc.poridhi.io
  resources:
  - vpcs/status
  verbs:
  - get
  - patch
  - update
