# permissions for end users to edit vpcs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: aws-vpc-controller
    app.kubernetes.io/managed-by: kustomize
  name: vpc-editor-role
rules:
- apiGroups:
  - vpc.poridhi.io
  resources:
  - vpcs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vpc.poridhi.io
  resources:
  - vpcs/status
  verbs:
  - get
